### ISSUE TITLE
As Ozzy, I need a dev environment

### ISSUE THREAD

**Issue by labofoz** [labofoz/labofoz#1]
## Overview
I have a difficult time with talking, and I haven't had any success at all with [SeeClarke.js](https://github.com/labofoz/seeclarke.js) despite obsessive around-the-clock work and several revisions. I have no income or money, and can't even afford the HDMI cable I need to test SeeClarke on [Google's AIYKits](https://aiyprojects.withgoogle.com/), which I believe is my final step to deploying truly affordable (basically free) accessibility tools for low-income individuals with disabilities.

So despite all this, I'm going to try streaming. However, because I have been completely socially isolated for almost 2 years now I cannot speak without feeling extremely anxious (or losing a gallon of precious water to sweating). To offset this, I will be streaming myself as a 3D Avatar, and speaking via Text to Speech.

I'll be using [VuePress](https://vuepress.vuejs.org/) as the blogging framework, and [A-Frame](https://aframe.io) for WebVR. This story deals specifically with setting up a basic environment.

## Inspriations
- http://otoro.net/ - I really love how Hardmaru uses his models as live showpieces
- Code Sandboxes like https://www.shadertoy.com/, https://glitch.com, and https://codepen.io

## Tasks
- [ ] Setup a basic VuePress site
- [ ] Add a hero area for the Aframe
- [ ] Load a basic scene into the Aframe
- [ ] Add some extremely basic
